---
apiVersion: v1
kind: Service
metadata:
  name: text-service
  labels:
    death-star-project: social-network
    app: text-service
  namespace: social-network
spec:
  ports:
  - port: 9090
  selector:
    death-star-project: social-network
    app: text-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: text-service
  labels:
    death-star-project: social-network
    app: text-service
  namespace: social-network
spec:
  replicas: 1
  selector:
    matchLabels:
      death-star-project: social-network
      app: text-service
  template:
    metadata:
      labels:
        death-star-project: social-network
        app: text-service
      name: text-service
    spec:
      containers:
      - name: text-service
        image: t.harbor.siat.ac.cn:100/library/social-network:v2.0
        command: ["TextService"]
        volumeMounts:
          - mountPath: /social-network-microservices/config/jaeger-config.yml
            subPath: jaeger-config.yml
            name: jaeger-conf-yaml
          - mountPath: /keys/CA.pem
            subPath: CA.pem
            name: ca-pem
          - mountPath: /keys/server.crt
            subPath: server.crt
            name: server-crt
          - mountPath: /keys/server.key
            subPath: server.key
            name: server-key
          - mountPath: /keys/server.pem
            subPath: server.pem
            name: server-pem
      restartPolicy: Always
      volumes:
        - name: jaeger-conf-yaml
          configMap:
            name: jaeger-config-yaml
        - name: ca-pem
          configMap:
            name: ca-pem
        - name: server-crt
          configMap:
            name: server-crt
        - name: server-key
          configMap:
            name: server-key
        - name: server-pem
          configMap:
            name: server-pem
